 fprintf(fseti,"\n");
 fprintf(fseti,"%d %ld %ld %d %d %d %d %d %d %d %d %d",
 s.Number,
 s.a1,s.a2,s.a4,s.a5,s.a6,s.a7,s.a8,s.a10[0],s.a10[1],
 s.a10[2],s.a10[3]);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d",
 s.a11[0],s.a11[1],s.a11[2],s.a11[3],s.a12[0],s.a12[1],s.a12[2],s.a12[3],
 s.a13[0],s.a13[1],s.a13[2],s.a13[3]);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d",
 s.a14,s.a15,s.a16,s.a17,s.a18,s.a19,s.a20,s.a21,s.a22,s.a23,s.a24,
 s.a25,s.a26,s.a27,s.a28,s.a29);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d",
 s.a30[0],s.a30[1],s.a30[2],s.a30[3],s.a31[0],s.a31[1],s.a31[2],s.a31[3],
 s.a32[0],s.a32[1],s.a32[2],s.a32[3]);
  fputs(s.a3,fseti);
