 fprintf(fseti,"\n");
 fprintf(fseti,"%d %ld %ld %d %d %d %d %d %d %d %d %d",
aa.Number,
 aa.a1,aa.a2,aa.a4,aa.a5,aa.a6,aa.a7,aa.a8,aa.a10[0],aa.a10[1],
 aa.a10[2],aa.a10[3]);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d",
 aa.a11[0],aa.a11[1],aa.a11[2],aa.a11[3],aa.a12[0],aa.a12[1],aa.a12[2],aa.a12[3],
 aa.a13[0],aa.a13[1],aa.a13[2],aa.a13[3]);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d",
 aa.a14,aa.a15,aa.a16,aa.a17,aa.a18,aa.a19,aa.a20,aa.a21,aa.a22,aa.a23,aa.a24,
 aa.a25,aa.a26,aa.a27,aa.a28,aa.a29);
 fprintf(fseti," %d %d %d %d %d %d %d %d %d %d %d %d",
 aa.a30[0],aa.a30[1],aa.a30[2],aa.a30[3],aa.a31[0],aa.a31[1],aa.a31[2],aa.a31[3],
 aa.a32[0],aa.a32[1],aa.a32[2],aa.a32[3]);
  fputs(aa.a3,fseti);
