    /* sscffedi.c */
 fscanf(fseti,"%d %d %d %d %d %d %d %d %d %d %d %d",
 &fe.nr,&fe.ns,&fe.mr,&fe.mxr,&fe.rb0,&fe.ny,&fe.nb,
	       &fe.kza,&fe.vzob,&fe.kn,&fe.tdir,&fe.rsrv);
  fscanf(fseti," %f %f %f %f %d %d %d %d %d %d %d %d",
 &fe.amn,&fe.amx,&fe.b1,&fe.b3,
 &fe.kk1,&fe.kk2,&fe.kk3,&fe.kk4,&fe.kk5,&fe.kk6,&fe.kk7,&fe.kk8);
  fscanf(fseti," %ld %ld %ld %d %d %d %d %d %d %d %d %d %d",
 &fe.kstan,&fe.dnd,&fe.dod,
 &fe.kagr,&fe.god1,&fe.dob,
 &fe.kk9,&fe.kk10,&fe.kk21,&fe.kk22,&fe.kk23,&fe.kk24,&fe.kk25);
  fscanf(fseti," %d %d %d %d %d %d %d",
 &fe.dr,&fe.dkr,
 &fe.kvd5,&fe.kvd6,
 &fe.kran,&fe.krem,
 &fe.rrq);